### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kriskowal** [uber/tcap#5]
- [ ] packet capture tracer
  - [x] basic frame capture and hex dump
  - [ ] structured dump of frames
    - [x] init request, init response, call request, call response
    - [ ] request continue, response continue
    - [ ] cancel, claim
    - [ ] ping request, ping response
    - [ ] error
  - [ ] support for structured arg display
